### PR TITLE
Migrate to nunit4

### PR DESCRIPTION
**Pull request by echoix**

### CODE REVIEW

**Comment by echoix** [comment]
Meant to target my fork before

**Comment by echoix** [comment]
There's still crashes of the test runner

**Comment by JohanLarsson** [comment]
Did not see this before, I dislike fluent syntax, so noisy. I'd rather migrate to xunit as the decision to break us made by nunit is unfortunate. I don't remember ever seeing any projects in the wild using fluent syntax.

**Comment by echoix** [comment]
No, I haven't seen this before. I'm glad we have the same opinion on fluent syntax. I didn't understand their move, and just kept using plain MsTest v2, it is largely enough and ends up having a similar syntax.

**Comment by echoix** [comment]
Since I ended up using Gu.Wpf.NumericInput for a project, do you mind having some more PRs to it to keep it alive and relevant? Its been working great, and works great also when targeting .NET 8 too (a change I have on my fork). It would be a way to give back

**Pull request closed without merging**
